In [1]:
import sys
import os
project_abspath = os.path.abspath("..")
sys.path.append(project_abspath)

from static.layers import Linear,Activation
from static.activations import tanh, sigmoid
from static.optimizers import SGD
from static.loss import MSE, SCE
from utils.dataset import shuffle
from utils.metrics import acc
from utils.ops import one_hot
from nn.net import SequentialNet
import numpy as np
from sklearn.datasets import load_boston, load_iris

# 1 回归

## [1.1 boston dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html)
    Samples total： 506
    Dimensionality：13
    Features：real, positive
    Targets：real 5. - 50.

In [2]:
from sklearn.preprocessing import normalize
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

# load data
boston = load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=0)
# preprocess
x_train = normalize(x_train, axis=0)
y_train = normalize(np.expand_dims(y_train, axis=1), axis=0)
print("train data size: ", x_train.shape, y_train.shape)
print("sample1:\n  x1: {}, \n  y1: {}".format(x_train[0], y_train[0]))

train data size:  (404, 13) (404, 1)
sample1:
  x1: [0.00202334 0.         0.02348504 0.18898224 0.04443475 0.05454761
 0.05908761 0.03307216 0.03115058 0.03491187 0.04656194 0.05273358
 0.03297787], 
  y1: [0.05439223]


In [3]:
# build model
reg = SequentialNet()
reg.add(Linear(input_dim=13, output_dim=4))
reg.add(Activation(tanh()))
reg.add(Linear(input_dim=4, output_dim=1))
reg.add(Activation(sigmoid()))
reg.compile(optimizer=SGD(lr=0.005), loss=MSE )
reg.show()

   Sequential Neural Network   
-------------------------------
> Linear Layer ((13, 4)) <
> Activation Layer (tanh) <
> Linear Layer ((4, 1)) <
> Activation Layer (sigmoid) <
-------------------------------


In [4]:
# train and eval
reg.fit(train_data=x_train, train_label=y_train, batch_size=64, epochs=20)

input size: (404, 13), target size:(404, 1)

epoch1 --------------------------------------------------
  batch1  batch_average_loss: 0.619215295670356
  batch2  batch_average_loss: 0.56884632484729
  batch3  batch_average_loss: 0.5135905456788594
  batch4  batch_average_loss: 0.4506689959183461
  batch5  batch_average_loss: 0.38952998280472517
  batch6  batch_average_loss: 0.3338909344208144
  batch7  batch_average_loss: 0.2696288022482045
epoch_average_loss: 0.44933869736979937

epoch2 --------------------------------------------------
  batch1  batch_average_loss: 0.25755544344307285
  batch2  batch_average_loss: 0.21607129629699828
  batch3  batch_average_loss: 0.17594773346441145
  batch4  batch_average_loss: 0.14647159464658668
  batch5  batch_average_loss: 0.12406984483784372
  batch6  batch_average_loss: 0.10814984631519454
  batch7  batch_average_loss: 0.0877486337970924
epoch_average_loss: 0.15943062754302856

epoch3 --------------------------------------------------
  batch1 

---

# 2 分类

## 2.1 [iris dataset](https://scikit-learn.org/0.16/modules/generated/sklearn.datasets.load_iris.html)
    Classes	3
    Samples per class	50
    Samples total	150
    Dimensionality	4

In [5]:
iris = load_iris()
# label one-hot encode
x, y = shuffle(iris.data, one_hot(iris.target, 3))
print("iris data size: ", x.shape, y.shape)
print("iris samples:\n  x1: {}, \n  y1: {}".format(x[:3], y[:3]))

iris data size:  (150, 4) (150, 3)
iris samples:
  x1: [[6.1 2.8 4.7 1.2]
 [5.7 4.4 1.5 0.4]
 [5.  3.4 1.6 0.4]], 
  y1: [[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [6]:
# build classifier model
clf = SequentialNet()
clf.add(Linear(input_dim=4, output_dim=3))
clf.add(Linear(input_dim=3, output_dim=3))
clf.compile(optimizer=SGD(lr=0.001), loss=SCE, metrics=acc)
clf.show()

   Sequential Neural Network   
-------------------------------
> Linear Layer ((4, 3)) <
> Linear Layer ((3, 3)) <
-------------------------------


In [7]:
# train and eval
clf.fit(train_data=x, train_label=y, batch_size=16, epochs=30)

input size: (150, 4), target size:(150, 3)

epoch1 --------------------------------------------------
  batch1  batch_average_loss: 2.897801366103038, metric: 0.5625
  batch2  batch_average_loss: 2.360210155828028, metric: 0.375
  batch3  batch_average_loss: 2.3770475352856484, metric: 0.625
  batch4  batch_average_loss: 1.5738315701696979, metric: 0.25
  batch5  batch_average_loss: 2.239748182689861, metric: 0.25
  batch6  batch_average_loss: 1.0229020585597746, metric: 0.75
  batch7  batch_average_loss: 1.09436577031651, metric: 0.6875
  batch8  batch_average_loss: 1.0429388177556045, metric: 0.4375
  batch9  batch_average_loss: 1.1056662620546596, metric: 0.25
  batch10  batch_average_loss: 1.1172728821874198, metric: 0.16666666666666666
epoch_average_loss: 1.6831784600950244
epoch_average_metric: 0.4354166666666667

epoch2 --------------------------------------------------
  batch1  batch_average_loss: 1.0200195614124792, metric: 0.5
  batch2  batch_average_loss: 1.0171500546707648

  batch4  batch_average_loss: 0.539389661607784, metric: 0.875
  batch5  batch_average_loss: 0.6624310194520605, metric: 0.875
  batch6  batch_average_loss: 0.638420110728162, metric: 0.5625
  batch7  batch_average_loss: 0.47418312884002056, metric: 0.9375
  batch8  batch_average_loss: 0.5345928195694838, metric: 0.875
  batch9  batch_average_loss: 0.7181230155160248, metric: 0.625
  batch10  batch_average_loss: 0.44001544189791614, metric: 0.8333333333333334
epoch_average_loss: 0.5830551608418977
epoch_average_metric: 0.8208333333333334

epoch18 --------------------------------------------------
  batch1  batch_average_loss: 0.5496945159866731, metric: 0.6875
  batch2  batch_average_loss: 0.4675311940565331, metric: 0.8125
  batch3  batch_average_loss: 0.5706554381112359, metric: 0.625
  batch4  batch_average_loss: 0.5830352909892929, metric: 0.875
  batch5  batch_average_loss: 0.5677081829395391, metric: 0.9375
  batch6  batch_average_loss: 0.5310891218158419, metric: 0.9375
  batch7